version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAM-Framework"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pe9r82h88rwl"
s3_prefix = "SAM-Framework"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
